### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by sdtaylor** [sdtaylor/PhenocamCNN2#2]
## manuscript:
- [x]  do data/software citations
- [x] need a table/map of sites
- [x] need some example images
- [x] need license statement for all phenocam images
- [x] cite Borowiec 2021 - https://doi.org/10.32942/osf.io/nt3as
- [x] new figure 1
- [x] fix precision: dom cover in accuracy figs

## rerun everything with:
- [x] sdtaylor/PhenocamCNN#6 sites excluded from the get go
- [x] other/fallow combined? Yes, only 86 images of fallow, 700+ of other
- [x] set the seed on held out data so they can be used later, or mark it in R somewhere
- [x] save val data frame for easier eval later
## Other things
- [x] deal with snow issue. If snow or water in dom category, then remove no crop in crop type and status just like removing blurry. Or actually changing to unknown sounds better. 
## organize folders/files
ie put A, B, C on folders for primary steps. prepend files with 1, 2, 3, etc.

**Comment by sdtaylor** [comment]
## Revision TODO

- [ ] cite MODIS Landcover HMM usage https://doi.org/10.1109/TGRS.2015.2463689

**Comment by sdtaylor** [comment]
published
